language: node_js
node_js:
  - "10"
services: docker
branches:
  only:
    - master
deploy:
  provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  region: 'ap-northeast-2'
  app: 'react-with-travis-docker-aws'
  env: 'ReactWithTravisDockerAws-env'
  bucket_name: 'react-with-travis-docker-aws'
notification:
  recipients:
    - yangtopia@gmail.com
